#!/usr/bin/env python

import sys

tut="Usage:\t cat sequence.fa | seqselect start finish \n \t or: seqselect sequence.fa start finish"

if len(sys.argv) < 3 or len(sys.argv) > 4:
	print tut
	sys.exit(1)

if len(sys.argv) == 3: 
	sstart=int(sys.argv[1])
	send=int(sys.argv[2])
elif len(sys.argv) == 4:
	fasta=sys.argv[1]
	sstart=int(sys.argv[2])
	send=int(sys.argv[3])

if not sys.stdin.isatty():
	for line in sys.stdin:
		if line[0] == ">":
			sys.stdout.write(line.strip("\n")+"_"+str(sstart)+"-"+str(send)+"\n")
		else:
			sys.stdout.write(line.strip("\n")[(sstart-1):send]+"\n")
else:
	with open(fasta,"r") as file_object:
		for line in file_object:
			if line[0] == ">":
				sys.stdout.write(line.strip("\n")+"_"+str(sstart)+"-"+str(send)+"\n")
			else:
				sys.stdout.write(line.strip("\n")[(sstart-1):send]+"\n")
		
### EOF ###
